# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chanhee Jeong
title: Computer Vision and Deep Learning Software Engineer
email: cris.j.dev@gmail.com
website: https://cris-j-dev.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: cris.j.dev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: cris-j-dev
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  AI 서비스 백엔드 아키텍쳐 설계 및 구축에 기여하고 싶습니다.
  첫 회사를 퇴사한 후 알고리즘에 대해 더 깊이 공부하고자 대학원 진학을 하였습니다. 운전 부주의로 인한 사고를 방지하기 위한 객체 상태 인식(운전자 상태 인식)연구에 가치를 느껴 휴먼컴퓨터인터랙션(HCI) 연구실에 합류하였습니다. 연구에 적용하기 위해 Lasagne/Caffe, Python을 배우며 딥러닝 세계에 접어들게 되었습니다. 
  딥 러닝을 이용하여 이미지 검색, 주가 예측, 화질 개선, 생체 신호 인식 등 다양한 프로젝트를 진행하였지만 아직 대중에게 필요한 서비스를 제공하지 못했다는 갈증이 있습니다.
  사람을 위한 가치, 그리고 그 가치를 위한 기술을 추구하며 개발자로서의 여정을 나아가고 있습니다. 사람들에게 가치를 주는 서비스 개발에 기여하여 발자취를 남기고 싶다는 갈증이 있습니다.

  `#C` `#C++` `#Python`  
  `#Linux` `#Network` `#Algorithm` `#Server` `#Docker`  
  `#Image-Processing` `#Signal-Processing`  
  `#Human-Computer-Interaction`  
  `#Machine-Learning` `#Deep-Learning`

content:
  - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 한국전자기술연구원(KETI)
        caption: 연구원
        date: 2019.02 ~ 현재
        quote: >
          휴먼IT융합연구센터에서 생체신호 및 영상 데이터 기반의 인공지능 및 기계학습 프로그램 개발
        description: | # this will include new lines to allow paragraphs
          - 뇌파 기반 집중력, 수면 분석 및 판단 알고리즘 개발
          - 호흡음 기반 감염병 판단 알고리즘 개발
          - EMG 기반 조산예측 알고리즘 개발
          - 영상 기반 피부상태 분석 알고리즘 개발
          - OCR 기반 신분증 분석 알고리즘 개발
          - 자연어 기반 사건-관계 추출 알고리즘 개발
          - 인프라 관리 및 연산 서버 개발

      - layout: left
        sub_title: (주)네오컨버전스
        caption: 대리
        date: 2017.08 ~ 2018.08
        quote: >
          IPTV 영상 개선 및 객체 검출/인식 알고리즘 연구 개발
        description: | # this will include new lines to allow paragraphs
          - 딥 러닝 기반 화질 개선 알고리즘 연구 개발
          - 딥 러닝 기반 해상도 향상 알고리즘 연구 개발
          - 영상 내 부분 모자이크 자동화 알고리즘 연구 개발
          - 화질 측정 솔루션 개발

      - layout: left
        sub_title: (주)버주어페브릭스
        caption: 사원
        date: 2016.04 ~ 2017.08
        quote: >
          이미지 기반의 의류 검색 엔진 개발 및 주가 예측 프로그램 개발
        description: | # this will include new lines to allow paragraphs
          - 주가 예측 및 자동 매수/매도 프로그램 개발
          - 윈도우 용 가상 가면 플랫폼 개발
          - 의류 이미지 검색 엔진 개발

      - layout: left
        sub_title: 세종대학교 일반대학원 컴퓨터공학과 HCI연구실
        caption: 석사
        date: 2014.03 ~ 2016.02
        quote: >
          HCI(Human Computer Interaction)연구실로 영상기반의 운전자 상태 판단 관련 연구
        description: | # this will include new lines to allow paragraphs
          - 운전자 상태 판단 시스템 개발
          - DBASM 얼굴 모델 연구 및 통풍 환자 판단 알고리즘 개발
          - MOSSE Filter 기반의 객체 추적 알고리즘 개발
          - Template Matching 기반 폐색 시 객체 추적 알고리즘 개발

  - title: 논문 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        quote: |
          MLOps의 하이퍼파라미터 최적화 알고리즘의 비교
        date: 2021.11
        caption: 추계종합학술
        sub_title: 한국통신학회

      - layout: left
        quote: |
          Comparison of PSD Correlation between HRV and PRV(Research Poster Papers)
        date: 2021.07
        caption: IEEE ENGINEERING IN MEDICINE AND BIOLOGY SOCIETY
        sub_title: EMBC

      - layout: left
        quote: |
          스마트폰 카메라를 이용한 손가락 PPG데이터 추출 시 색 공간에 대한 비교 분석 연구
        date: 2021.06
        caption: 하계종합학술대회
        sub_title: 한국통신학회

      - layout: left
        quote: |
          집중력 향상 모니터링을 위한 뇌파 측정 및 분석 시스템
        date: 2020.11
        caption: 추계종합학술대회
        sub_title: 한국통신학회

      - layout: left
        quote: |
          심전도와 광용적맥파의 심박변이도 유사성 연구
        date: 2020.11
        caption: 추계학술대회
        sub_title: 대한전자공학회

      - layout: left
        quote: |
          다양한 환경에서의 뇌파 분석을 통한 집중도 분석 연구
        date: 2020.02
        caption: 동계종합학술대회
        sub_title: 한국통신학회

      - layout: left
        quote: |
          조산 위험도 예측을 위한 STFT 기반의 자궁 수축 모니터링 알고리즘 연구
        date: 2019.06
        caption: 하계종합학술대회
        sub_title: 한국통신학회

  - title: 특허 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        caption: 산업통산자원부
        sub_title: 출원
        date: 2020.11.27
        quote: |
          임상적 유효성을 갖는 TES 기반 다감각 자극을 이용한 스트레스 케어 기기 개발 및 서비스 기술 개발
        description: |
          - 뇌파 데이터 기반 수면 단계 분석 방법

      - layout: left
        caption: 산업통산자원부
        sub_title: 출원
        date: 2021.11.26
        quote: |
          모바일 기반 비대면 정신건강 케어를 위한 디지털 치료제 조기 사업화 기술 개발
        description: |
          - 스마트 폰 카메라 영상 기반의 PPG 복원 방법 및 장치

      - layout: left
        caption: 산업통산자원부
        sub_title: 출원
        date: 2021.11.29
        quote: |
          임상적 유효성을 갖는 TES 기반 다감각 자극을 이용한 스트레스 케어 기기 개발 및 서비스 기술 개발
        description: |
          - 뇌파를 통한 인공지능 기반 수면단계 검출 방법

        - layout: left
        caption: 과학기술정보통신부
        sub_title: 출원
        date: 2021.12.31
        quote: |
          감염성 호흡기 질환 셀프 모니터링이 가능한 스마트 패치 및 다중생체정보 분석 알고리즘 기술개발
        description: |
          - 생체신호 기반 감염성 호흡기 질환 모니터링 방법 및 시스템
          - 스마트폰 카메라 기반의 PPG를 이용한 감염성 호흡기 질환 감염 위험도 탐지방법

  - title: 저작권 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        caption: 산업통산자원부
        sub_title: 프로그램등록
        date: 2020.05.19
        description: |
          - 뇌파 기반 수면 패턴 분석 프로그램
          - 뇌파 뷰어 및 집중도 계산 프로그램

      - layout: left
        caption: 과학기술정보통신부
        sub_title: 프로그램등록
        date: 2021.12.16
        description: |
          - 생체정보 분석 인공지능 소프트웨어
          - 생체신호 데이터 전처리 및 뷰어 소프트웨어
          - 감염성 호흡기 질환 모델 검증 소프트웨어
          - 생체신호 데이터 수집 백엔드 소프트웨어

  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 한국전자기술연구원(KETI)
        date: 2019.02.01 ~ 현재
        main: DR.G AI 피부 분석 및 7종 피부 지표 분석 알고리즘 개발
        quote: |
          AI 기반 얼굴 피부 분석 알고리즘 및 7종 피부 지표 분석 알고리즘 개발
        enviroment: Linux, Python, OpenCV, Mediapipe, Docker, Flask
        description: |
          - 딥 러닝을 이용하여 피부 분석 및 유분, 수분, 모공, 여드름, 주름, 홍조, 색소침착  등 7가지 피부 지표 분석 알고리즘 개발.  
          ![image09](./images/image09.png)

      - layout: left
        main: 감염성 호흡기 질환자 다중 생체 정보 분석 알고리즘 개발
        quote: |
          코로나 환자의 생체 정보 분석 알고리즘 개발
        enviroment: Linux, Python, Flask, Redis, MariaDB
        description: |
          - 심박수, 체온, 산소포화도, 호흡율, 심박변이도, 호흡음 등 6종의 생체신호를 측정하여 데이터 수집 및 저장 가능한 DB 서버 및 알고리즘 서버 개발생체 신호를 딥 러닝/머신 러닝을 이용하여 학습앙상블 모델을 적용하여 위험도를 판단하는 알고리즘 개발 및 서버 구축.  
          ![image08](./images/image08.png)

      - layout: left
        main: 인공지능 그랜드 챌린지 인프라 구축
        quote: |
          인공지능 그랜드 챌린지 인프라 구축
        enviroment: Linux, Python, Go, Docker, RabbitMQ
        description: |
          - 인공지능 그랜드 챌린지 인프라 중 참가자의 도커 파일을 생성 및 빌드, 실행하여 결과를 도출하는 자동화 서버 개발도커 파일 메이커, 도커 파일 빌드를 수행하는 2가지 기능이 핵심이며 메시지큐를 이용하여 서버 동기화 개발.  
          ![image07](./images/image07.png)

      - layout: left
        main: 코로나 환자 뷰어 앱 개발
        quote: |
          GPS 기반 코로나 환자 발생자 뷰어 앱 개발
        enviroment: Linux, HTML, CSS, Javascript, React-Native, Python, Flask
        description: |
          - GPS 위치를 기반으로 주변 지역의 환자 발생 현황을 보여주는 안드로이드 앱 개발환자.  
          ![image06](./images/image06.png)

      - layout: left
        main: 신분증 인식 OCR 서버 프로그램
        quote: |
          스마트폰으로 촬영된 신분증 정보를 OCR을 이용하여 인식하는 프로그램 개발
        enviroment: Linux,  C++, Python, Docker, FastAPI
        description: |
          - 오픈소스 라이브러리인 EasyOCR을 환경에 맞게 수정 개발라이브러리 형태로 Python개발 및 Docker Image 구성.  
          ![image05](./images/image05.png)

      - layout: left
        main: RestAPI 다감각 자극을 이용한 스트레스 케어 기기 개발
        quote: |
          뇌파 등 생체신호를 측정하여 스트레스 분석 솔루션
        enviroment: Linux,  Python
        description: |
          - 헤드밴드 형 웨어러블 기기를 이용하여 사람의 EEG, PPG의 생체신호를 수집하여 신호처리 및 딥 러닝/머신 러닝을 이용하여 스트레스 판단1

      - layout: left
        main: 조산 예측 프로그램
        quote: |
          조산 가능성 예측 지원 솔루션
        enviroment: Linux,  Python
        description: >
          - 임산부의 근육 수축을 딥 러닝으로 예측하여 조산의 가능성을 분석하는 시스템을 개발 중. 현재 예측 모델을 개발하여 기존 예측방법과 성능 비교 테스트 진행.

      - layout: left
        main: 브레인피트니스
        quote: |
          뇌파를 이용한 집중, 수면 상태 향상 가이드 솔루션
        enviroment: Windows,  Python,  QT
        description: |
          - 사람의 뇌파를 분석하여 집중도, 수면상태 등을 분석하여 집중도 향상과 수면의 질 향상을 위한 가이드를 제공하는 솔루션을 개발 중. 현재 뇌파를 수집할 수 있는 소프트웨어를 개발. 사용자의 외부모습을 캠으로 녹화 및 동시에 3채널의 뇌파를 저장 가능.

      - layout: left
        main: 맥진기 SW 개발
        quote: |
          맥 진단 의료 지원 소프트웨어
        enviroment: Linux,  C++,  QT
        description: |
          - 사람의 맥박을 감지할 수 있는 하드웨어 센서에 맞는 소프트웨어. 센서에서 24채널의 데이터를 받아 맥박이 뛰는 것을 실시간 모니터링이 가능하고, 또한 센서에서 HRV 신호를 받아 의료진이 필요한 분포도, 히스토그램, 스펙트럼 밀도 등을 분석할 수 있는 기능을 개발.
          ![image04](./images/image04.png)

      - layout: left
        sub_title: (주)네오컨버전스
        date: 2017.08 ~2018.08
        main: 딥 러닝을 이용한 동영상 화질 개선 및 해상도 향상 솔루션
        quote: |
          딥 러닝으로 동영상의 화질 개선 및 해상도 향상(HD->FHD->UHD)
        enviroment: Ubuntu16.04,  Python,  C++,  FFmpeg
        description: >
          - 저화질 영상과 고화질 영상을 학습하여 화질 개선과 해상도를 향상하였으며, 동영상을 디코딩하여 프레임을 추출한 후 화질 개선 및 해상도 향상함.(YUV 기존 필터를 이용한 화질 개선 및 해상도 향상 프로그램은 사람이 손으로 필터를 만들 어야 하는 단점이 있었지만 본 프로젝트를 기법을 이용한 프로그램은

      - layout: left
        main: 부분 모자이크 처리 솔루션
        quote: |
          동영상에 부적절한 객체(담배, 칼, 여성의 가슴 등)를 검출 후 모자이크
        enviroment: Ubuntu16.04,  Python,  C++,  FFmpeg,  OpenCV
        description: |
          - 동영상에 부적절한 객체를 검출, 모자이크하는 솔루션. YOLO v2를 적용. 디코딩 후 3프레임 당 1장씩만 검출하여 적용, OpenCV를 이용하여 모자이크(블러) 처리를 하여 인코딩함.

      - layout: left
        main: 퍼타이틀(PERTITLE) 솔루션
        quote: |
          영상의 화질의 정도를 측정하는 퍼타이틀(PERTITLE) 솔루션
        enviroment: Ubuntu16.04,  Python,  FFmpeg
        description: |
          - 기존의 PSNR/SSIM/MS_SSIM 등 다양한 화질 측정 알고리즘과 Netflix의 VMAF를 통합하여 영상의 화질을 측정하는 솔루션. 화질을 측정하고 사람이 보기에 보통 정도의 화질의 Bitrate를 추천해주는 솔루션. 사용자가 스마트기기에서 스트리밍으로 볼 때 부하를 적게 하고 최상의 화질로 영상을 감상할 수 있도록 도와줌.

      - layout: left
        sub_title: 버추어패브릭스
        date: 2016.04 ~2017.08
        main: 주가 예측 및 자동 매수/매도 프로그램
        quote: |
          딥 러닝을 활용한 주가 예측 및 자동 매수/매도 프로그램
        enviroment: Windows,  Ubuntu14.04,  Python
        description: |
          - 주가 예측을 위해 증권사 API를 이용한 크롤링 시스템 개발. 3년 치의 데이터를 수집, LSTM을 이용하여 학습을 하였고 분 단위로 매수/매도 및 가격을 예측할 수 있게 개발. 일반적인 시장 예측은 가능하나 원하는 수량을 매수/매도하기 어려웠고 매수/매도가 즉각 이루어지지 않아서 수익은 잘 나지 않았음(모의주식enviroment: 에서는 20%의 수익을 얻음). 사회 현상을 반영하기 위해 기사 수집 및 자연어처리를 하여 기사의 주요 단어와 연관 회사를 매칭하여 긍/부정을 통해 정확도를 향상시킴. 하지만 역시 원하는 순간에 매수/매도가 잘 진행되지 않아 수익률은 1.5% 정도로 개발을 종료.

      - layout: left
        main: 윈도우 용 가상 가면 플랫폼
        quote: |
          가상 캠을 이용한 가상 가면 프로그램
        enviroment: Windows,  C++,  MFC,  Python
        description: |
          - SNOW와 같은 가상 가면을 씌우는 윈도우용 플랫폼 개발. 기존의 얼굴 검출 알고리즘과 가상 가면 알고리즘을 결합하여 개발. ASM 얼굴모델을 이용하여 3D가면의 Shape을 적용. 아프리카TV와 같이 가상 캠을 이용한 곳에서 사용할 수 있게 개발이 되었고 가면과 다양한 이모티콘을 띄울 수 있게 개발되었음. 가면과 이모티콘 등의 효과는 제공받았으며, MFC와 Python, 가상 캠, DB 연동을 직접 구현.  
          ![image03](./images/image03.png)

      - layout: left
        main: 의류 이미지 검색 엔진 개발
        quote: |
          딥 러닝 기반 의류 검색 엔진 개발
        enviroment: Ubuntu14.04,  Python,  Theano,  Keras
        description: |
          - 기존의 검색 방법은 의류에 태깅하여 분류하는 방법을 이용. 본 엔진에 사용된 방법은 이미지 자체를 학습하여 사용자가 원하는 옷과 비슷한 색상, 디자인의 옷을 검색해주는 엔진. 크롤링하여 다양한 웹 사이트의 옷 이미지와 URL을 수집하여 DB를 구성하고 이미지의 특징 벡터를 생성. 특징 벡터 생성 시 색상과 디자인을 따로 분류하여 생성하고 따로 학습을 진행. 해외 의류는 약 90% 이상의 정확도를 보였으나 국내 의류는 75% 정도의 정확도를 보임. 국내 의류는 배경도 많고 수집 시 분류되는 디자인의 이름이 쇼핑몰 마다 다르게 표기 되어 같은 디자인의 의류라도 다르게 불리고 있는 단점이 있음. 초기 DB 생성 시 잘못 분류되어 벡터가 잘못 생성되는 것이 많은 오류를 가지고 있는 것으로 파악되었고 국내 의류는 태깅을 함께 이용하여 고도화를 진행.

      - layout: left
        sub_title: 세종대학교 석사과정HCI
        date: 2014. 03 ~2016. 02
        main: 운전자 상태 판단 시스템(Convolutional Neural Network)
        quote: |
          CNN을 이용한 운전자 상태 판단 시스템
        enviroment: Ubuntu12.04,  Windows,  Python,  C++,  Caffe,  OpenCV
        description: >
          - ImageNet 2014에 사용된 VGGnet를 기본으로 실시간 운전자 상태 판단 시스템을 개발. 운전자의 시선 위치를 총 8곳으로 나누어 데이터셋을 구성하였고 이를 학습시켜 실시간으로 시선을 판단하게 개발. 사람의 머리 포즈(3D-Yaw, Pitch, Rall)를 단일 카메라로 판단 가능. 사람의 머리에 센서를 부착하여 카메라로 촬영된 머리 이미지와 3축의 각도를 동시에 얻어 트레이닝 데이터셋으로 구성. 약 1.5도 오차. 얼굴 특징점을 얻을 수 있어 눈 깜빡임과 하품 등의 상태를 판단 가능. 운전자 상태 판단을 모두 CNN을 이용하여 구성. 단일 카메라로 하품, 졸음 (머리의 각도), 시선(시선 부주의) 등을 판단. 기존에는 다양한 센서를 이용했어야 했지만 단일 카메라로 구성할 수 있다는 것이 가장 큰 장점.    
          ![image02](./images/image02.png)

      - layout: left
        main: DBASM(Discriminative Bayesian Active Shape Model)
        quote: |
          기존 ASM + MOSSE FILTER를 적용한 얼굴 모델
        enviroment: Windows,  C++,  OpenCV
        description: |
          - 기존 ASM 얼굴 모델의 각 특징점에 MOSSE Filter를 적용하여 특징점 자체를 추적하여 만드는 얼굴 모델. 특징점의 MOSSE Filter가 업데이트 되어 폐색 상황에서도 지속적인 얼굴 모델 제작 가능. 얼굴 모델이 추적할 수 있기 때문에 POSE Estimation도 가능. 부분적인 움직임에도 얼굴 모델 제작이 가능하기 때문에 전남대와 연계하여 통풍 환자의 얼굴을 보고 병의 유무를 판단할 수 있는 프로그램을 개발.   
          ![image01](./images/image01.png)

      - layout: left
        main: MOSSE Filter(Minimum Output Sum of Squared Error)
        quote: |
          변화에 강인한 객체 추적 알고리즘
        enviroment: Windows,  Matlab,  C++
        description: |
          - FFT를 이용하여 이미지를 주파수 도메인으로 변경하여 필터 제작. 필터를 이용하여 현재 위치에서 가장 비슷한 곳으로 필터가 이동. 폐색, 회전, 조명변화 등으로 찾으려는 객체의 변화에도 주파수 도메인으로 변경된 필터에는 큰 영향을 미치지 않아 지속적인 추적 가능.

      - layout: left
        main: AAM(Active Appearance Model)
        quote: |
          차량 내부에서 단일 카메라를 이용한 얼굴 특징점의 변화 검출
        enviroment: Windows,  C++,  OpenCV
        description: |
          - 차량 내부에서 운전자의 상태를 파악하여 졸음운전, 전방 부주의 등을 판단하기 위한 연구를 진행. 운전자의 상태 파악을 위해 눈의 변화, 입의 변화, 얼굴 각도 등이 필요. 여기에 적용하기 위해 AAM 모델을 사용하였고 얼굴 특징점 58개를 학습. 다양한 얼굴 사진을 구하고 58개의 얼굴 특징점을 생성 후 학습, PCA를 이용하여 평균 Shape를 계산. 일반적인 상황에서 얼굴  특징점 추출이 가능해짐.

      - layout: left
        main: Adaptive Template Matching(적응형 템플릿 매칭)
        quote: |
          폐색에 강인한 객체 추적 시스템
        enviroment: Windows,  C++,  OpenCV
        description: |
          - 기본적인 템플릿 매칭을 이용한 객체 추적시스템은 객체의 변화에 매우 취약함. 이를 극복하기 위해 템플릿을 주기적으로 업데이트를 시키는 방법을 고안. 업데이트의 조건으로 Outlier 개념를 추가하여 Outlier의 수치가 일정 수준 이상 발생하면 템플릿을 업데이트 시킴. 추가적으로 Kalman Filter를 이용하여 이전 템플릿과의 업데이트 되는 템플릿의 차이를 줄여 급격한 템플릿 변화를 방지. 폐색의 면적을 20%, 40%, 60%로 증가하면서 실험을 진행. 기존 템플릿 매칭 은 약 75%, 50%, 15%의 정확도를 보였으며 적응형 템플릿 매칭은 약 90%, 85%, 78%의 정확도를 보여 향상시킴. 템플릿 매칭의 계산속도로 인하여 실시간 적용이 어려움.

  - title: 외부 활동 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 대회
        caption: Pytorch Korea (Runners-up 수상)
        date: 2019.01.06
        quote: >
          PyTorch KR Tutorial Competition 2018
        description: |
          - PYTORCH를 이용한 딥 러닝 네트워크 구현 대회 - YOLO 구현

      - layout: left
        sub_title: 강의
        caption: 멀티캠퍼스 / SAFFY / Elice
        date: 2018.12.17 ~ 2018.12.21
        quote: >
          삼성 청년 소프트웨어 아카데미(SAFFY) – 챗봇 제작
        description: |
          - 간단한 슬랙 챗봇을 만들어 보자

      - layout: left
        sub_title: 강의
        caption: LG전자
        date: 2018.10.08 ~ 2018.10.12
        quote: >
          LG전자 직무전환자 교육
        description: |
          - Tensorflow를 사용한 딥 러닝 기초 강의

      - layout: left
        sub_title: 대회
        caption: Open Medical Image Computing
        date: 2018.04
        quote: >
          Gastrointestinal Image Analysis
        description: |
          - 의학영상을 이용한 종양검출 (GIANADataset 사용)

      - layout: left
        sub_title: 대회
        caption: 정보통신기술진흥센터
        date: 2018.04 ~ 2018.06
        quote: >
          2018년도 인공지능 R&D 챌린지
        description: |
          - 합성사진 검출 대회 참가

      - layout: left
        sub_title: 강의
        caption: 멀티캠퍼스
        date: 2018.01
        quote: >
          실전!TensorFlow로 배우는 딥러닝
        description: |
          - Tensorflow를 사용한 딥 러닝 기초 강의

      - layout: left
        sub_title: 연구실
        caption: 모두의 연구소
        date: 2018.07 ~ 2018.09
        quote: >
          파이리101(파이썬, 리눅스)
        description: |
          - 리눅스, 파이썬 및 네트워크 기초 강좌

      - layout: left
        sub_title: 연구실
        caption: 모두의 연구소
        date: 2018.01 ~ 2018.04
        quote: >
          Deep Lab Edu 5th
        description: |
          - 딥 러닝 기초 연구실 (교재: 밑바닥부터 시작하는 딥 러닝 / 멘토)

      - layout: left
        sub_title: 기고문
        caption: 마이크로 소프트웨어
        date: 2017.01
        quote: >
          Caffe를 이용한 객체 분류
        description: |
          - CAFFE를 이용한 딥 러닝 학습 모델 구성 실습

      - layout: left
        sub_title: 강의
        caption: LG전자
        date: 2016.12
        quote: >
          Deep Learning Software
        description: |
          - 딥 러닝 소프트웨어 비교 및 설명 (CAFFE를 이용한 딥 러닝 학습 모델 실습)

      - layout: left
        sub_title: 시연
        caption: 국립과천과학관
        date: 2016.10.08
        quote: >
          무한상상 2016 메이커랜드 축제
        description: |
          - 관상 – 내 눈을 바라봐 (딥 러닝을 이용한 나이, 성별, 감정 인식)

      - layout: left
        sub_title: 발표
        caption: CDE학회 튜토리얼
        date: 2016.08.25
        quote: >
          Deep Learning Tools (Theano, Caffe, TensorFlow)
        description: |
          - 다양한 딥 러닝 툴 비교 및 설명

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
